### ISSUE TITLE
Cannot find module 'ngx-credit-cards'

### ISSUE THREAD

**Issue by aliminurudeen** [zenkkor/ngx-credit-cards#1]
Good day, am trying to use ngx-credit-cards in my project and am getting this error
"Cannot find module 'ngx-credit-cards'"

**Comment by nichovski** [comment]
+1

**Comment by juddfranklin1** [comment]
+1

**Comment by juddfranklin1** [comment]
Ultimately, I got past this issue by manually adding the .ts content (directives folder, validators folder, index.ts, and ngxcreditcard.module.ts) to the root directory of the node_modules/ngx-credit-cards directory.

Now, I get messages saying that the directives and validator cannot find the module 'payment' which I installed as a node package, so I'm rooting around for a solution once more.

**Comment by zenkkor** [comment]
Guys, really sorry. I just saw this today. I'll take a look at it ASAP and post a fix. It probably has something to do with the way it's bundled for the AOT version.

**Comment by elliottsaray** [comment]
@zenkkor any update?

**Comment by zenkkor** [comment]
@elliottsaray sorry, I had zero time for this because I was booked full time. If anyone else is willing to fix this i'll gladly accept a PR.

**Comment by paulocoliver** [comment]
I downloaded the project and build again
worked for me
https://www.npmjs.com/package/gc-ngx-credit-cards
