### ISSUE TITLE
Issue with build in angular 4

### ISSUE THREAD

**Issue by maitham1** [zenkkor/ngx-credit-cards#2]
Hey there,
DOes this support angular 4, as I keep getting ngc check failed:  

https://stackoverflow.com/questions/43945912/angular-module-failing-ngc-check-no-idea-why

**Comment by ziemerz** [comment]
I'm having te exact same error when AOT transpiling Angular 4.x

**Comment by nwrman** [comment]
Same here, I think it's just a minor detail, but I just can't grasp my head around it.

**Comment by lucaswxp** [comment]
same here

**Comment by maitham1** [comment]
I ended up just pulling the methods I needed from their library into my own TS files rather than importing the library

**Comment by slavafomin** [comment]
Is this module maintained?

**Comment by nwrman** [comment]
I did what @maitham1 suggested and it's working flawlessly :)

**Comment by zenkkor** [comment]
Merged a PR from a user so should be good now

**Comment by Keko94** [comment]
I reopen this ticket because the bug doesn't seem to be fixed:
When I run in dev mode, it works, but in prod mode, it doesn't work anymore.

[23:28:39]  build prod started ... 
[23:28:39]  clean started ... 
[23:28:39]  clean finished in 2 ms 
[23:28:39]  copy started ... 
[23:28:39]  deeplinks started ... 
[23:28:39]  deeplinks finished in 123 ms 
[23:28:39]  ngc started ... 
[23:28:42]  typescript error 
            Unexpected value 'NgXCreditCardsModule in 
            /Users/keko/Documents/pharma/node_modules/ngx-credit-cards/index.js' imported by the module 'AppModule in 
            /Users/keko/Documents/pharma/src/app/app.module.ts'. Please add a @NgModule annotation. 

I use Ionic with Angular 5

**Comment by jayeshkorat18** [comment]
+1 I use Ionic 3 with Angular 5 same issue

**Comment by guilherme22** [comment]
Using angular 5.3 and the same error here.

**Comment by dentkachuk** [comment]
angular 6
+1

**Comment by botoxparty** [comment]
Angular 6 & 7 +1

**Comment by timmyrosen** [comment]
Angular 7 +1

**Comment by keriroso** [comment]
I create a modules folder.
![Captura de Pantalla 2020-06-21 a la(s) 01 26 03](https://user-images.githubusercontent.com/8844367/85218345-0b3c7d00-b35f-11ea-9c0b-fb46209b3900.png)

add app.module.ts and in the 'imports'
import { NgXCreditCardsModule } from '../module/ngx-credit-cards/ngxcreditcard.module';

also remove 'fns' in the directives
  Payment.formatCardExpiry(element);
  Payment.restrictNumeric(element);
