### ISSUE TITLE
Can't compile the project with i18n

### ISSUE THREAD

**Issue by abhilashrathod** [zenkkor/ngx-credit-cards#3]
Hello there, 
I was trying to apply i18n in my angular app and met this error...

`Unexpected value 'NgXCreditCardsModule in /path/to/project/node_modules/ngx-credit-cards/index.d.ts' imported by the module 'AppModule in /path/to/project/src/app/app.module.ts'. Please add a @NgModule annotation.`

Project config: 

- Angular: 4.0.3
- Typescript: 2.3.4
- Node: 7.7.1
- NPM: 4.1.2

Could you please help me with this?
Thanks.

**Comment by nwrman** [comment]
Hey @abhilashrathod have you found a way around this?

**Comment by abhilashrathod** [comment]
@nwrman I used your directive files and created my own @NgModule and added them as a part of my project and it worked..!

**Comment by zenkkor** [comment]
Merged a PR from a user so should be good now

**Comment by aditdeveloper** [comment]
@abhilashrathod We are getting same issue. can you share example ?

**Comment by abhilashrathod** [comment]
@aditdeveloper Nothing much I did there, I took all the `src` files from this repo and created my own custom angular module. Imported and exported all modules. Imported that module in my main app.module and everything worked fine as expected.
