### ISSUE TITLE
ERROR TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Kemaweyan** [zenkkor/ngx-credit-cards#6]
Calls to `payment` functions compiled as undefined. For instance in `CCNumberFormatDirective` the code

```
// call lib functions
Payment.formatCardNumber(element);
Payment.restrictNumeric(element);
```

in JS file becomes 

```
// call lib functions
undefined(element);
undefined(element);
```

**Comment by davidpp** [comment]
Same issue here

**Comment by Keko94** [comment]
Same since the last update

**Comment by MoBehrouzifar** [comment]
same issue: ERROR TypeError: undefined is not a function

**Comment by jitendra1681** [comment]
Same issue with me please make a solution

**Comment by MatissJanis** [comment]
I've fixed the issue and submitted a PR for it: https://github.com/zenkkor/ngx-credit-cards/pull/7

Hopefully it gets merged & published soon!

**Comment by kshkrao3** [comment]
Did this change got committed? I am still getting the error. So I thought to confirm before raising the issue. 

I am seeing 1.0.8 version.

**Comment by zenkkor** [comment]
@MatissJanis @kshkrao3 This has been republished now as version 1.0.9.

@MatissJanis  thank you again!

**Comment by kshkrao3** [comment]
@zenkkor Thank you so much.. 👍

**Comment by kshkrao3** [comment]
Well, am getting this error in my console now - **Payment.fns.restrictNumeric is not a function**.

**Comment by ryan0122** [comment]
I"m also getting the Payment.fns.restrictNumeric is not a function error. 

When I do a console.log of Payment.fns that method isn't listed. Here is the output:

```
cardExpiryVal :ƒ (value)
cardType: ƒ (num)
formatCardNumber :ƒ (num)
validateCardCVC: ƒ (cvc, type)
validateCardExpiry: ƒ (month, year)
validateCardNumber: ƒ (num)
```

**Comment by jayeshkorat18** [comment]
i am also getting this error in my console - **TypeError: Payment.fns.restrictNumeric is not a function**

**Comment by GetTaxSolutions** [comment]
We also have this error. The function Payment.fns.restrictNumeric is not available from payment library.
